// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSbvXNvp7j_jzQiNpxDsqAhuOxgVguxY',
    appId: '1:24997189923:web:d2b8e4e92d025cb6fa1496',
    messagingSenderId: '24997189923',
    projectId: 'sophie-app-513f2',
    authDomain: 'sophie-app-513f2.firebaseapp.com',
    storageBucket: 'sophie-app-513f2.appspot.com',
    measurementId: 'G-EKSJ6V0WW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJhbk1nGosQWtLTA9BJTkG0i8q51sffM',
    appId: '1:24997189923:android:dab2d6349881d20ffa1496',
    messagingSenderId: '24997189923',
    projectId: 'sophie-app-513f2',
    storageBucket: 'sophie-app-513f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6BFVH4hDCQAN68WnGzVNVbr7JCIztm_8',
    appId: '1:24997189923:ios:ba6d785b95158c8efa1496',
    messagingSenderId: '24997189923',
    projectId: 'sophie-app-513f2',
    storageBucket: 'sophie-app-513f2.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6BFVH4hDCQAN68WnGzVNVbr7JCIztm_8',
    appId: '1:24997189923:ios:afbf0d5b2088a5acfa1496',
    messagingSenderId: '24997189923',
    projectId: 'sophie-app-513f2',
    storageBucket: 'sophie-app-513f2.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
